[versions]
# libraries
annotations = "24.1.0"
okHttpClient = "4.12.0"
kotlinxSerializationJson = "1.6.2"

# plugins
kotlin = "1.9.21"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.3"
qodana = "0.1.13"
kover = "0.7.5"
kotlinSerializationPlugin = "1.9.21"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
okHttpClient = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttpClient" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kotlinSerializationPlugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializationPlugin" }
